# version: "3.13" !!! в новых версиях Docker указывать версию не требуется !!!

services: # сервисы
  db:
    container_name: "pg_dev" # имя контейнера
    image: postgres:16.2-alpine3.18 # образ базы данных
    environment: # переменные окружения
      - POSTGRES_USER=${PG_USER} # присвоение должно быть без пробелов вокруг знака равно!!!!
      - POSTGRES_PASSWORD=${PG_PASSWORD} # присвоение должно быть без пробелов вокруг знака равно!!!!
      - POSTGRES_DB=${PG_DATABASE} # присвоение должно быть без пробелов вокруг знака равно!!!!
    ports:
      - "5433:5432" # порт базы данных и порт Докера
    networks:
      - networking # имя сети
    restart: always # тип рестарта при неисправностях
networks: # сети
  networking: # имя сети
    driver: bridge # используемый драйвер
